### ISSUE TITLE
Installation on windows 7 x64

### ISSUE THREAD

**Issue by CrackerakiUA** [webBoxio/atom-term2#139] opened 2015-06-29 10:27 UTC
Installing “term2@0.9.9” failed.Hide output…

> pty.js@0.2.7-1 install C:\Users\Crack\AppData\Local\Temp\apm-install-dir-115529-7904-pwr4zh\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\Crack\AppData\Local\Temp\apm-install-dir-115529-7904-pwr4zh\node_modules\term2\node_modules\pty.js>node "C:\Users\Crack\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Crack\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Crack\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Crack\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Crack\\.atom\\.apmrc" "install" "C:\\Users\\Crack\\AppData\\Local\\Temp\\d-115529-7904-1w2qodj\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by thomasantony** [comment] 2015-06-30 18:17
I have this same problem on Mac OSX 10.9.5. The debug log file that the error message told me to get didn't exist.

    Installing term2 to /Users/tantony/.atom/packages ✗

    > pty.js@0.2.7-1 install /private/var/folders/xv/6plqjz6n56q6ss_z69gvz0dh0000gp/T/apm-install-dir-115530-44470-1sghj9l/node_modules/term2/node_modules/pty.js
    > node-gyp rebuild


    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at maybeClose (child_process.js:766:16)
    gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
    gyp ERR! stack     at Socket.emit (events.js:95:17)
    gyp ERR! stack     at Pipe.close (net.js:466:12)
    gyp ERR! System Darwin 13.4.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /private/var/folders/xv/6plqjz6n56q6ss_z69gvz0dh0000gp/T/apm-install-dir-115530-44470-1sghj9l/node_modules/term2/node_modules/pty.js
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Darwin 13.4.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tantony/.atom/.apm/.apmrc" "--userconfig" "/Users/tantony/.atom/.apmrc" "install" "/private/var/folders/xv/6plqjz6n56q6ss_z69gvz0dh0000gp/T/d-115530-44470-1ba5eb1/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the pty.js package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls pty.js
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/xv/6plqjz6n56q6ss_z69gvz0dh0000gp/T/apm-install-dir-115530-44470-1sghj9l/npm-debug.log

**Comment by MoOx** [comment] 2015-07-01 11:57
>  npm ERR! This is most likely a problem with the pty.js package,

Please open an issue on their repository

**Comment by MoOx** [comment] 2015-07-01 12:06
Duplicate of #132

**Closed by MoOx** 2015-07-01 12:06 UTC
