### ISSUE TITLE
term2 0.9.4 doesn't works under win32.

### ISSUE THREAD

**Issue by lygstate** [webBoxio/atom-term2#99] opened 2015-03-17 19:07 UTC
C:\CI-Cor\ks>apm install term2
Installing term2 to C:\Users\lygstate\.atom\packages failed

> pty.js@0.2.6 install C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-115218-11116-agxp2c\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-115218-11116-agxp2c\node_modules\term2\node_modules\pty.js>node "C:\CI-Tools\IDE\Atom\resources\a
pp\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-115218-11116-agxp2c\node_modules\term2\node_modules\p
ty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\CI-Tools\\IDE\\Atom\\resources\\app\\apm\\bin\\\\node.exe" "C:\\CI-Tools\\IDE\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\n
pm-cli.js" "--globalconfig" "C:\\Users\\lygstate\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\lygstate\\.atom\\.apmrc" "install" "C:\\Users\\lygst
ate\\AppData\\Local\\Temp\\d-115218-11116-1xi8dch\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

C:\CI-Cor\ks>

**Comment by Jonjoe** [comment] 2015-03-27 22:30
Term wont work with windows as its a bash terminal (unix). Youll need a Linux distro or OSX.

**Comment by MoOx** [comment] 2015-07-01 12:19
Duplicate of #132

**Closed by MoOx** 2015-07-01 12:19 UTC
