### ISSUE TITLE
Prompt over output

### ISSUE THREAD

**Issue by matugm** [webBoxio/atom-term2#27] opened 2014-07-05 13:35 UTC
The output doesn't look right when executing a simple command. Manjaro Linux, Atom 0.107

![image](https://cloud.githubusercontent.com/assets/1369748/3486653/110dfebe-0449-11e4-9bb1-b2fe0a686073.png)

**Comment by MoOx** [comment] 2015-07-01 12:26
Duplicate of #77

**Closed by MoOx** 2015-07-01 12:26 UTC
