### ISSUE TITLE
Won't install on Windows 8.1 64Bit Python 3.4

### ISSUE THREAD

**Issue by blankclemens** [webBoxio/atom-term2#136] opened 2015-06-20 01:25 UTC
> pty.js@0.2.7-1 install C:\Users\Clemens\AppData\Local\Temp\apm-install-dir-115520-3692-1u8x3i6\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\Clemens\AppData\Local\Temp\apm-install-dir-115520-3692-1u8x3i6\node_modules\term2\node_modules\pty.js>node "C:\Users\Clemens\AppData\Local\atom\app-0.210.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Clemens\\AppData\\Local\\atom\\app-0.210.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Clemens\\AppData\\Local\\atom\\app-0.210.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Clemens\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Clemens\\.atom\\.apmrc" "install" "C:\\Users\\Clemens\\AppData\\Local\\Temp\\d-115520-3692-1vp905v\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by bojidar-bg** [comment] 2015-06-25 09:12
https://github.com/webBoxio/atom-term2/issues/90 ?

**Comment by MoOx** [comment] 2015-07-01 12:06
Duplicate of #132

**Closed by MoOx** 2015-07-01 12:06 UTC

**Comment by blankclemens** [comment] 2015-07-01 12:08
Thank you, I didn't want to create real attention, the feedback button just appeared after it crashed and I thought it might be some automatic error collection for the statistics. Sorry.

**Comment by MoOx** [comment] 2015-07-01 12:10
No problem. Please go to #132, follow the link to the issue on pty.js and tell them you want windows bin ^^

**Comment by blankclemens** [comment] 2015-07-01 12:20
Done :)
