### ISSUE TITLE
Failed to activate the term2 package

### ISSUE THREAD

**Issue by imalitavakoli** [webBoxio/atom-term2#160] opened 2015-07-18 14:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.13

### Stack Trace

Failed to activate the term2 package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ali\.atom\packages\atom-term2\lib\TermView.coffee:4:14)
  at Object.<anonymous> (C:\Users\Ali\.atom\packages\atom-term2\lib\TermView.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ali\.atom\packages\atom-term2\index.coffee:2:12)
  at Object.<anonymous> (C:\Users\Ali\.atom\packages\atom-term2\index.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:709:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:257:12)
  at Package.module.exports.Package.activateNow (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:236:14)
  at C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Ali\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:02.1.0 term2:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "Linter",
      "emmet-atom",
      "linter-write-good",
      "autocomplete-php",
      "atom-ctags",
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.4
emmet, v2.3.12
file-icons, v1.5.7
linter, v0.12.7
linter-bootlint, v0.0.6
linter-jshint, v0.1.6
linter-php, v0.0.15
linter-scss-lint, v1.0.4
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by MoOx** [comment] 2015-07-19 17:15
Duplicate of the issue you already opened #122

**Closed by MoOx** 2015-07-19 17:15 UTC
