### ISSUE TITLE
Term2 sets up path incorrectly

### ISSUE THREAD

**Issue by MikaAK** [webBoxio/atom-term2#51] opened 2014-09-16 19:27 UTC
I just installed Term2 for atom and it looks amazingly promising. However my `PATH` in my shell `fish` looks as such
````
/usr/local/opt/rbenv/shims /usr/local/opt/rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/var/rbenv/shims
````

but when I open up Term2 for atom my `PATH` is changed to 
````
/usr/local/opt/rbenv/shims /usr/local/opt/rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/var/rbenv/shims
````

I feel this could be a result of atom-Term2 not working well with [Fish Shell](fishshell.com) though fish does open inside of atom-Term2 its `PATH` is incorrectly set!

**Comment by lordofthelake** [comment] 2015-06-26 10:51
Better workaround: in Term2 Preferences, set "Shell Arguments" to `-l` (basically the same thing as `login`, but avoids spawning a second shell)

**Comment by MoOx** [comment] 2015-07-01 12:23
Duplicate of #50

**Closed by MoOx** 2015-07-01 12:23 UTC
